/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_FXOS8700CQ_H
#define _JERRYSCRIPT_MBED_FXOS8700CQ_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

#include "FXOS8700CQ.h"

DECLARE_CLASS_CONSTRUCTOR(FXOS8700CQ);
jerry_value_t mbed_js_wrap_native_object(FXOS8700CQ* ptr);

#endif // _JERRYSCRIPT_MBED_FXOS8700CQ_H
