/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_LIB_FXOS8700CQ_H
#define _JERRYSCRIPT_MBED_LIB_FXOS8700CQ_H

#include "mbed-js-fxos8700cq/mbed-js-fxos8700cq.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

void mbed_js_FXOS8700CQ_setup();

DECLARE_JS_WRAPPER_REGISTRATION (fxos8700cq)
{
    REGISTER_CLASS_CONSTRUCTOR(FXOS8700CQ);
    mbed_js_FXOS8700CQ_setup();
}

#endif // _JERRYSCRIPT_MBED_LIB_FXOS8700CQ_H
