/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#include "jerryscript-mbed-util/logging.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

#include "FXOS8700CQ.h"

/**
 * FXOS8700CQ#enable (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, enable) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, enable, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        native_ptr->enable();
        return jerry_create_undefined();
    }
}

/**
 * FXOS8700CQ#disable (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, disable) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, disable, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        native_ptr->disable();
        return jerry_create_undefined();
    }
}

/**
 * FXOS8700CQ#get_whoami (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, get_whoami) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, get_whoami, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        uint8_t result = native_ptr->get_whoami();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#status (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, status) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, status, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        uint8_t result = native_ptr->status();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#get_data (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, get_data) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, get_data, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        uint8_t result = native_ptr->get_data();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#get_accel_scale (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, get_accel_scale) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, get_accel_scale, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        uint8_t result = native_ptr->get_accel_scale();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getAccelX (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getAccelX) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getAccelX, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getAccelX();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getAccelY (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getAccelY) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getAccelY, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getAccelY();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getAccelZ (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getAccelZ) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getAccelZ, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getAccelZ();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getMagnetX (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getMagnetX) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getMagnetX, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getMagnetX();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getMagnetY (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getMagnetY) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getMagnetY, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getMagnetY();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#getMagnetZ (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(FXOS8700CQ, getMagnetZ) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, getMagnetZ, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        FXOS8700CQ* native_ptr = reinterpret_cast<FXOS8700CQ*>(ptr_val);
    
    
    
        int16_t result = native_ptr->getMagnetZ();
        return jerry_create_number(result);
    }
}

/**
 * FXOS8700CQ#destructor
 *
 * Called if/when the FXOS8700CQ is GC'ed.
 */
void NAME_FOR_CLASS_NATIVE_DESTRUCTOR(FXOS8700CQ)(const uintptr_t native_handle) {
    delete reinterpret_cast<FXOS8700CQ*>(native_handle);
}


/**
 * mbed_js_wrap_native_object (turns a native FXOS8700CQ object into a JS object)
 */
jerry_value_t mbed_js_wrap_native_object(FXOS8700CQ* ptr) {
    uintptr_t native_ptr = (uintptr_t) ptr;

    jerry_value_t js_object = jerry_create_object();
    jerry_set_object_native_handle(js_object, native_ptr, NAME_FOR_CLASS_NATIVE_DESTRUCTOR(FXOS8700CQ));

    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, enable);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, disable);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, get_whoami);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, status);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, get_data);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, get_accel_scale);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getAccelX);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getAccelY);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getAccelZ);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getMagnetX);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getMagnetY);
    ATTACH_CLASS_FUNCTION(js_object, FXOS8700CQ, getMagnetZ);

    return js_object;
}

/**
 * FXOS8700CQ (native JavaScript constructor)
 */
DECLARE_CLASS_CONSTRUCTOR(FXOS8700CQ) {
    CHECK_ARGUMENT_COUNT(FXOS8700CQ, __constructor, (args_count == 3));

    if (args_count == 3) {
        CHECK_ARGUMENT_TYPE_ON_CONDITION(FXOS8700CQ, __constructor, 0, number, (args_count == 3));
        CHECK_ARGUMENT_TYPE_ON_CONDITION(FXOS8700CQ, __constructor, 1, number, (args_count == 3));
        CHECK_ARGUMENT_TYPE_ON_CONDITION(FXOS8700CQ, __constructor, 2, number, (args_count == 3));
    
        PinName arg0 = PinName(jerry_get_number_value(args[0]));
        PinName arg1 = PinName(jerry_get_number_value(args[1]));
        double jArg2 = jerry_get_number_value(args[2]);
        int arg2 = static_cast<int>(jArg2);
    
        // Create the native object
        FXOS8700CQ* native_obj = new FXOS8700CQ(arg0, arg1, arg2);
    
        return mbed_js_wrap_native_object(native_obj);
    }
}

void mbed_js_FXOS8700CQ_setup() {

}
